package cr.ac.ucr.parchis.view;
import java.awt.event.ActionListener;

//Clase que contiene las creditos del juego
public class GUICreditos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUICreditos.class.getName());

    
    public GUICreditos() {
        initComponents();
    }
    
    //Se encarga de asignar al controller los metodos de ActionListener de los botones 
    public void setListener(ActionListener controller){
        this.btnAtrasCreditos.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtrasCreditos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasCreditos.setBackground(new java.awt.Color(205, 88, 96));
        btnAtrasCreditos.setFont(new java.awt.Font("Linux Biolinum G", 0, 24)); // NOI18N
        btnAtrasCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasCreditos.setText("Atras");
        btnAtrasCreditos.setActionCommand("Atras Creditos");
        getContentPane().add(btnAtrasCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, 120, -1));

        jLabel1.setFont(new java.awt.Font("Linux Biolinum G", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(205, 88, 96));
        jLabel1.setText("Desarrollado por: ana :>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aesthetic.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUICreditos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
