package cr.ac.ucr.parchis.view;
import java.awt.event.ActionListener;

//Panel que contiene los botones de inicio
public class PanelButtons extends javax.swing.JPanel {

    
    public PanelButtons() {
        initComponents();
    }
    
    //Se encarga de asignar al controller los metodos de ActionListener de los botones 
    public void setListener(ActionListener controller){
        this.btnCreditos.addActionListener(controller);
        this.btnHistoria.addActionListener(controller);
        this.btnInstruc.addActionListener(controller);
        this.btnJugar.addActionListener(controller);
        this.btnSalir.addActionListener(controller);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnInstruc = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        btnJugar.setBackground(new java.awt.Color(205, 88, 96));
        btnJugar.setFont(new java.awt.Font("Linux Biolinum G", 0, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");

        btnInstruc.setBackground(new java.awt.Color(205, 88, 96));
        btnInstruc.setFont(new java.awt.Font("Linux Biolinum G", 0, 24)); // NOI18N
        btnInstruc.setForeground(new java.awt.Color(255, 255, 255));
        btnInstruc.setText("Instrucciones");

        btnCreditos.setBackground(new java.awt.Color(205, 88, 96));
        btnCreditos.setFont(new java.awt.Font("Linux Biolinum G", 0, 24)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Creditos");

        btnHistoria.setBackground(new java.awt.Color(205, 88, 96));
        btnHistoria.setFont(new java.awt.Font("Linux Biolinum G", 0, 24)); // NOI18N
        btnHistoria.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoria.setText("Historia");

        btnSalir.setBackground(new java.awt.Color(205, 88, 96));
        btnSalir.setFont(new java.awt.Font("Linux Biolinum G", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btnInstruc, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btnHistoria, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInstruc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstruc;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables
}
